name = "SpecialArrays"
uuid = "dced3ab1-7816-4ad4-9c7c-956aa26e9cbf"
authors = ["Colin Summers", "The Contributors of SpecialArrays"]
version = "0.1.0"

[compat]
julia = "1.4"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
